### PR TITLE
Feature/59 case variables

### PR DESCRIPTION
**Pull request by jangalinski**
Adds support for variable access on caseService.

see #59 

- [x] implement factories
- [x] implement adapters
- [x] finalize tests
- [x] add documentation

### CODE REVIEW

**Comment by jangalinski** [comment]
@zambrovski If I do not hear objections, I will merge and release tomorrow ... need this feature at work asap.

**Comment by zambrovski** [comment]
Wait for me 

Simon Zambrovski
Dipl.-Ing.-Inf. 

Mobile: +49 176 1616 9010
E-Mail: simon@zambrovski.org
Internet: http://simon.zambrovski.org/

**Comment by zambrovski** [comment]
Bad idea to combine change of formatting (actually why was is needed?) with functional features. 

It looks ok to me, the continuous decrease of coverage is kind of weak, but it is not solely the problem of your change. Still, we started with above 80% and are below 60% now... more complexity and less tests seems to be a risky path. 

Free to merge...

**Comment by jangalinski** [comment]
> Bad idea to combine change of formatting (actually why was is needed?) with functional features.

No idea why this wasn't formatted correctly in the first place ... should have been handled by the editorconfig

no examples ... cmmn is an edge case ... might add some later

**Comment by zambrovski** [comment]
Hm. The editor config says 2 spaces not 4. Are you sure you applied the correct formatter?

**Comment by jangalinski** [comment]
will check ... can you just fix it?

**Comment by zambrovski** [comment]
No. I have a cellphone only.

**Comment by jangalinski** [comment]
ah. :-)

ok ... will do

**Comment by jangalinski** [comment]
will do reformatting in separated pr ... to much clutter

**Comment by zambrovski** [comment]
Probably, a defined formatter is king!

I asked you for one some time ago if you remember. For now I picked the default IDEA IntelliJ with Editor config...

**Comment by jangalinski** [comment]
> I asked you for one some time ago if you remember

yes, i know. see #61   but combined formatting of java/kotlin and formatting that matches codacy are still unsolved issues.

I will merge this and do a follow-up push with correct formatting

**Pull request merged**
