### PR TITLE
Allow nullable types in Kotlin

### LINKED ISSUE #394: Allow nullable variable types from Kotlin
### Steps to reproduce

* camunda-bpm-data version: 1.4.0
* Camunda BPM version: 7.20.0
* JDK version:  17
* Operating system: MacOs

### Expected behaviour

When the library was implemented in Java, it was possible to set a variable to `null`, due to somewhat relaxed interoperability rules. 

### Actual behaviour

Now I can't find a way to do that. The boundary for the type parameter `T` of a variable factory is `Any`, not `Any?`, so I can't create a Variable Factory for a nullable type. The `set` methods take a `T` argument, not `T?`, so I can't put `null` in there. The best I can do is to remove the variable if the value is `null`, but that is cumbersome. Also it's not the same thing if a variable doesn't exist at all as when the variable exists with value `null`.

It would also be nice to have some convenience functions like `setIfNotNull` or `setOrRemove` to not interrupt the flow of fluent variable writing.

I'm posting this as a bug because it's a regression and major breaking change compared to the Java implementation.

### PR DESCRIPTION
**Pull request by zambrovski**
Fix #394 

I believe it is not the bound which needs to be changed, since Java `String` means StringOrNull on set.

### CODE REVIEW

**Comment by zambrovski** [comment]
@lbilger and @jangalinski since you both observed the bug, I created a proposal how to fix this. Please review and give me some comments - and please try it out in your environment.

**Comment by lbilger** [comment]
@zambrovski thanks for the proposal. This change basically changes the methods of the adapters so that an adapter of type `T : Any` can read/write values of type `T?`, i.e. also handle null values. That means every variable access is treated as nullable and the caller has to handle null results.

There's a strong argument that this is correct because there is no way to statically prove that a variable is not null. Also, it will often be null at some point of the process even if it is non-null at another point. Of course, the type cannot be statically proven either, but if you persistently use BPM Data then you can assume that if the variable is set at all, it will have this type.

Still, I want to raise the question if it wouldn't be more convenient to continue letting the methods take / return `T`, but use `Any?` as the upper bound for `T`. Then you could express nullable or non-nullable variables through the type parameter of the variable factory. Then it is up to the user if they want to see null values as something that the program can handle (e.g. by using a default value) or as a programming error (where they would throw an `IllegalStateException` or something similar anyway).

VariableFactories should probably be considered nullable by default, so e.g. `CamundaBpmDataKotlin.stringVariable` would return `VariableFactory<String?>`. You could then offer methods to turn a nullable `VariableFactory` into a non-nullable one, e.g. `fun <T> VariableFactory<T?>.withDefault(default: T): VariableFactory<T>` or `fun <T> VariableFactory<T?>.assertNonNull(): VariableFactory<T>`.
 
All of this still does not take into account the difference between an absent variable and a variable that is present with value `null`, but I currently have no good idea how to make that distinction and if it is even worthwhile. I am inclined to think it would be bad practice to rely on this distinction.

**Comment by zambrovski** [comment]
I had all this in mind as I suggested the change - you are completely right. Nevertheless, try this solution with your code base and tell me if it breaks. I assume - it is not. And even more - since the get methods return `T` and the setters allow `T?` you won't need to change anything. So in terms of a bugfix and restoring the previous behavior, it is a valid solution and a solution without need to change code.

The other thing is - technically it is not just changing the bounds. It is not so trivial as it looks like. By the way - I also considered that the change is only applicable to `BasicFactory` but not to parameterized factories... So `List<String?>`, `Set<String?>`, Map<Sting?, String?>`makes no sense to me. Even more, a `List<String>?`, `Set<String>?`, `Map<String, String>?` neither - in the current implementation I allow to set null to those and then set empty collections instead of null underneath.

P.S. my primary goal is to RESTORE the previous behavior we had as it was implemented in Java.    This is probably different to FIXING wrong behavior. Please do me a favor and try to use 1.4.1-SNAPSHOT built locally and report if everything is "working" as before migration of the library to Kotlin...

**Comment by zambrovski** [comment]
>  That means every variable access is treated as nullable and the caller has to handle null results.

This is not quite correct. The getter is still returning `T`, the setter allows to set null

**Comment by zambrovski** [comment]
Took the approach proposed by @lbilger and implementen in #407

**Pull request closed without merging**
